@startuml
class com.example.notmyapplication.UserPrescriptioDocView {
~ String userKey
~ Button b
~ RecyclerView recyclerView
~ user u
~ ArrayList<Meds> medsList
~ DatabaseReference databaseReference
~ FirebaseDatabase firebaseDatabase
# void onCreate(Bundle)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
+ void onItemClick(int)
+ void onClick(View)
}
class com.example.notmyapplication.Meds {
- String medName
- Integer amount
- Double price
- String expDate
+ <<Create>> Meds(String,Double,String)
+ <<Create>> Meds()
+ String getMedName()
+ void setMedName(String)
+ Integer getAmount()
+ void setAmount(Integer)
+ Double getPrice()
+ void setPrice(Double)
+ String getExpDate()
+ void setExpDate(String)
+ String toString()
}
class com.example.notmyapplication.med_select_for_doc {
~ String userKey
~ RecyclerView recyclerView
~ Meds m
~ ArrayList<Meds> medsList
~ DatabaseReference databaseReference
~ FirebaseDatabase firebaseDatabase
~ boolean updated
# void onCreate(Bundle)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
+ void onItemClick(int)
}
class com.example.notmyapplication.Doc_User_List {
- {static} int PICK_FROM_GALLERY
~ ArrayList<user> rewardArrayList1
~ RecyclerView list_rewards1
~ DatabaseReference databaseReference
~ user r
~ FirebaseDatabase firebaseDatabase
# void onCreate(Bundle)
}
interface com.example.notmyapplication.interface_for_adapter {
~ void onItemClick(int)
}
class com.example.notmyapplication.ConnectDocToUser {
~ boolean updated
~ RecyclerView recyclerView
~ user u
~ ArrayList<user> UsersList
~ DatabaseReference databaseReference
~ FirebaseDatabase firebaseDatabase
# void onCreate(Bundle)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
+ void onItemClick(int)
}
class com.example.notmyapplication.med_adapter {
- interface_for_adapter interface_for_adapter
~ Context context
~ ArrayList<Meds> ItemsList
~ StorageReference storageReference
+ <<Create>> med_adapter(Context,ArrayList<Meds>,interface_for_adapter)
+ med_adapter.MyViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(med_adapter.MyViewHolder,int)
+ int getItemCount()
}
class com.example.notmyapplication.med_adapter.MyViewHolder {
~ TextView medName
+ <<Create>> MyViewHolder(View,interface_for_adapter)
}
class com.example.notmyapplication.doc_reg {
~ EditText docName
~ EditText docPass
~ EditText docEmail
~ EditText docPhone
~ FirebaseAuth firebaseAuth
~ FirebaseDatabase firebaseDatabase
~ Button b
~ ProgressDialog p
~ DatabaseReference myref
# void onCreate(Bundle)
+ void createDoctor()
+ boolean isValidate()
+ void onClick(View)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.notmyapplication.Doc {
- String docName
- String docPass
- String docEmail
- String docKey
- String docPhone
- ArrayList<String> userList
+ <<Create>> Doc(String,String,String,String,String)
+ <<Create>> Doc(String,String,String,String,String,ArrayList<String>)
+ <<Create>> Doc()
+ void AddUserKeyToDoc(String)
+ String getDocName()
+ String getDocPassWord()
+ String getDocEmail()
+ String getDocKey()
+ ArrayList getUserList()
+ String getDocPhone()
+ void setDocName(String)
+ void setDocPassWord(String)
+ void setDocEmail(String)
+ void setDocKey(String)
+ void setUserList(ArrayList<String>)
+ void setDocPhone(String)
+ String toString()
}
class com.example.notmyapplication.prescription_userSide {
~ Button b
~ RecyclerView recyclerView
~ user u
~ ArrayList<Meds> medsList
~ DatabaseReference databaseReference
~ FirebaseDatabase firebaseDatabase
# void onCreate(Bundle)
+ void onClick(View)
+ void onItemClick(int)
}
class com.example.notmyapplication.user_login {
~ EditText name
~ Button b3
~ String password
~ String mail
~ String Name
~ SharedPreferences sp
~ CheckBox rem
# void onCreate(Bundle)
+ void logIn()
+ void onClick(View)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.notmyapplication.Message {
- String text
- String FromUser
+ <<Create>> Message(String,String)
+ <<Create>> Message()
+ String getText()
+ void setText(String)
+ String getFromUser()
+ void setFromUser(String)
+ String toString()
}
class com.example.notmyapplication.user {
- String name
- String pass
- String email
- String key
- ArrayList<Meds> medlist
- String pic
- String Phone
+ <<Create>> user(String,String,String,String,String,String)
+ <<Create>> user()
+ String getUserName()
+ String getPassWord()
+ String getEmail()
+ String getKey()
+ ArrayList<Meds> getMedlist()
+ String getPhone()
+ void setUserName(String)
+ void setPassWord(String)
+ void setEmail(String)
+ void setKey(String)
+ void setMedlist(ArrayList<Meds>)
+ void addToMedlist(Meds)
+ String getPic()
+ void setPic(String)
+ void setPhone(String)
+ String toString()
}
class com.example.notmyapplication.UserRegister {
+ {static} int PICK_FROM_GALLERY
~ EditText name
~ EditText pass
~ EditText email
~ EditText phone
~ ImageView pic
~ String picName
~ Uri uri
~ FirebaseAuth firebaseAuth
~ FirebaseDatabase firebaseDatabase
~ StorageReference mStorageRef
~ Button b
~ ProgressDialog p
~ DatabaseReference myref
~ ActivityResultLauncher<Intent> someActivityResultLauncher
# void onCreate(Bundle)
+ void CreateUser()
+ boolean isValidate()
+ void onClick(View)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
- void handlePermission()
- String getFileExtension(Uri)
+ void onActivityResult(int,int,Intent)
}
class com.example.notmyapplication.Splash {
# void onCreate(Bundle)
}
class com.example.notmyapplication.users_of_doc {
~ boolean updated
~ RecyclerView recyclerView
~ user u
~ ArrayList<user> UsersList
~ DatabaseReference databaseReference
~ FirebaseDatabase firebaseDatabase
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
+ void onItemClick(int)
}
class com.example.notmyapplication.DUL_adapter {
- interface_for_adapter interface_for_adapter
~ Context context
~ ArrayList<user> ItemsList
+ <<Create>> DUL_adapter(Context,ArrayList<user>,interface_for_adapter)
+ DUL_adapter.MyViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(DUL_adapter.MyViewHolder,int)
+ int getItemCount()
}
class com.example.notmyapplication.DUL_adapter.MyViewHolder {
~ TextView name
+ <<Create>> MyViewHolder(View,interface_for_adapter)
}
class com.example.notmyapplication.chat {
~ ImageView sendMessege
~ EditText text
~ ArrayAdapter<String> adapter
~ ArrayList<String> list
~ ArrayList<Message> listpost
~ ArrayAdapter<Message> lpadapter
~ ListView myListView
~ DatabaseReference myref
~ ProgressDialog p
~ BottomNavigationView bottomNav
~ Message message
~ FirebaseDatabase firebaseDatabase
~ FirebaseAuth firebaseAuth
# void onCreate(Bundle)
+ void createMSG()
+ boolean isValidate()
}
class com.example.notmyapplication.MedsReg {
- {static} String TAG
~ EditText name
~ TextView expDate
~ Button b3
~ DatePickerDialog.OnDateSetListener mDateSetListener
~ FirebaseAuth firebaseAuth
~ FirebaseDatabase firebaseDatabase
~ ProgressDialog p
~ DatabaseReference myref
# void onCreate(Bundle)
+ void CreateMed()
+ void onClick(View)
}
class com.example.notmyapplication.doc_login {
~ EditText name
~ Button b3
~ String docPassword
~ String docMail
~ String docName
~ SharedPreferences sp
~ CheckBox rem
# void onCreate(Bundle)
+ void logIn()
+ void onClick(View)
}
class com.example.notmyapplication.MainActivity {
~ SharedPreferences spU
~ FirebaseAuth firebaseAuth
~ Intent in
~ BottomNavigationView bottomNav
~ BottomNavigationView bottomNavUser
# void onCreate(Bundle)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}


com.example.notmyapplication.interface_for_adapter <|.. com.example.notmyapplication.UserPrescriptioDocView
com.example.notmyapplication.OnClickListener <|.. com.example.notmyapplication.UserPrescriptioDocView
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.UserPrescriptioDocView
com.example.notmyapplication.interface_for_adapter <|.. com.example.notmyapplication.med_select_for_doc
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.med_select_for_doc
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.Doc_User_List
com.example.notmyapplication.interface_for_adapter <|.. com.example.notmyapplication.ConnectDocToUser
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.ConnectDocToUser
com.example.notmyapplication.Adapter <|-- com.example.notmyapplication.med_adapter
com.example.notmyapplication.med_adapter +.. com.example.notmyapplication.med_adapter.MyViewHolder
com.example.notmyapplication.ViewHolder <|-- com.example.notmyapplication.med_adapter.MyViewHolder
com.example.notmyapplication.OnClickListener <|.. com.example.notmyapplication.doc_reg
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.doc_reg
java.io.Serializable <|.. com.example.notmyapplication.Doc
com.example.notmyapplication.interface_for_adapter <|.. com.example.notmyapplication.prescription_userSide
com.example.notmyapplication.OnClickListener <|.. com.example.notmyapplication.prescription_userSide
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.prescription_userSide
com.example.notmyapplication.OnClickListener <|.. com.example.notmyapplication.user_login
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.user_login
java.io.Serializable <|.. com.example.notmyapplication.user
com.example.notmyapplication.OnClickListener <|.. com.example.notmyapplication.UserRegister
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.UserRegister
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.Splash
com.example.notmyapplication.interface_for_adapter <|.. com.example.notmyapplication.users_of_doc
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.users_of_doc
com.example.notmyapplication.Adapter <|-- com.example.notmyapplication.DUL_adapter
com.example.notmyapplication.DUL_adapter +.. com.example.notmyapplication.DUL_adapter.MyViewHolder
com.example.notmyapplication.ViewHolder <|-- com.example.notmyapplication.DUL_adapter.MyViewHolder
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.chat
com.example.notmyapplication.OnClickListener <|.. com.example.notmyapplication.MedsReg
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.MedsReg
com.example.notmyapplication.OnClickListener <|.. com.example.notmyapplication.doc_login
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.doc_login
androidx.appcompat.app.AppCompatActivity <|-- com.example.notmyapplication.MainActivity
@enduml